# Generated by Django 3.0.9 on 2020-08-05 10:27

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookKeeping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Статья')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/')),
            ],
            options={
                'verbose_name': 'Полезная бухгалтерия',
                'verbose_name_plural': 'Полезная бухгалтерия',
            },
        ),
    ]
