# Generated by Django 3.0.9 on 2020-08-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200806_1124'),
        ('bookkeeping', '0002_auto_20200805_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeping',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookkeepings_set', to='main.Section', verbose_name='Раздел'),
        ),
    ]
