# Generated by Django 3.0.9 on 2020-08-12 10:40

import base.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_bookkeeping_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeping',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='bookkeeping/audio'),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(help_text='Допустимый формат - .pdf', null=True, upload_to='bookkeeping/documents', verbose_name='Файл'),
        ),
    ]
