# Generated by Django 3.0.9 on 2020-08-13 08:37

import base.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_auto_20200812_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeping',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='bookkeeping/audio', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(blank=True, help_text='Допустимый формат - .pdf', null=True, upload_to='bookkeeping/documents', verbose_name='Файл'),
        ),
    ]
