# Generated by Django 3.0.9 on 2020-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_auto_20200814_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeping',
            name='type',
            field=models.CharField(default='Аудиозапись', max_length=20, verbose_name='Тип'),
        ),
    ]
