# Generated by Django 3.0.9 on 2021-04-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_auto_20210417_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookkeepingstatistics',
            options={'verbose_name': 'Статистика просмотра полезной бухгалтерии', 'verbose_name_plural': 'Статистика просмотра полезной бухгалтерии'},
        ),
    ]
