# Generated by Django 3.0.9 on 2021-04-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0015_auto_20210417_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingstatistics',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего просмотров'),
        ),
    ]
