# Generated by Django 3.0.9 on 2021-04-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0016_bookkeepingstatistics_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingListenStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookkeeping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_listen_statistics', to='bookkeeping.BookKeeping', verbose_name='Полезная бухгалтерия')),
            ],
            options={
                'verbose_name': 'Статистика прослушиваний полезной бухгалтерии',
                'verbose_name_plural': 'Статистика прослушиваний полезной бухгалтерии',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingListenStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_listen_statistics_months', to='bookkeeping.BookkeepingListenStatistics', verbose_name='Полезная бухгалтерия')),
            ],
            options={
                'verbose_name': 'Статистика прослушиваний полезной бухгалтерии за месяц',
                'verbose_name_plural': 'Статистика прослушиваний полезной бухгалтерии за месяц',
            },
        ),
    ]
