# Generated by Django 3.0.9 on 2021-04-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0017_bookkeepinglistenstatistics_bookkeepinglistenstatisticsmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookkeepingstatistics',
            options={'verbose_name': 'Статистика просмотра полезной бухгалтерии', 'verbose_name_plural': 'Статистика просмотров полезной бухгалтерии'},
        ),
    ]
