# Generated by Django 3.0.9 on 2020-08-05 10:22

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='EduHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Краткая информация')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eduheads_set', to='main.Section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Глава',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(default='', max_length=13, verbose_name='Телефон')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Адрес')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyers_set', to='edu.EduHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Юрист',
                'verbose_name_plural': 'Юристы',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_set', to='edu.EduHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Куда обращаться',
                'verbose_name_plural': 'Куда обращаться',
            },
        ),
        migrations.CreateModel(
            name='EduEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Статья')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_set', to='edu.EduHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('phone', models.CharField(default='', max_length=13, verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Почта')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts_set', to='edu.City', verbose_name='Город')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts_set', to='edu.Entity', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
    ]
