# Generated by Django 3.0.9 on 2020-08-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduentry',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='eduhead',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
