# Generated by Django 3.0.9 on 2020-08-06 07:50

import base.extra
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20200805_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduentry',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(help_text='Допустимый формат - .pdf', null=True, upload_to='base/documents', verbose_name='Файл'),
        ),
    ]
