# Generated by Django 3.0.9 on 2020-08-07 07:44

import base.extra
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20200807_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduentry',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(help_text='Допустимый формат - .pdf', null=True, upload_to='edu/documents', verbose_name='Файл'),
        ),
    ]
