# Generated by Django 3.0.9 on 2020-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20200807_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduentry',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='edu/audio'),
        ),
    ]
