# Generated by Django 3.0.9 on 2020-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20200904_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduhead',
            name='type',
            field=models.CharField(choices=[('audio', 'Аудиозапись'), ('lawyer', 'Юрист'), ('organisation', 'Организация')], default='audio', max_length=20, verbose_name='Тип'),
        ),
    ]
