# Generated by Django 3.0.9 on 2020-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_auto_20201111_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduentry',
            name='audio_image',
            field=models.FileField(blank=True, null=True, upload_to='edu/images', verbose_name='Фото для аудио'),
        ),
    ]
