# Generated by Django 3.0.9 on 2021-04-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_eduentrystatistics_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduEntryListenStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edu_entry_listen_statistics', to='edu.EduEntry', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика прослушиваний статьи',
                'verbose_name_plural': 'Статистика прослушиваний статей',
            },
        ),
        migrations.AlterModelOptions(
            name='eduentryfilestatisticsmonth',
            options={'verbose_name': 'Статистика скачиваний файлов статьи за месяц', 'verbose_name_plural': 'Статистика скачиваний файлов статьи за месяц'},
        ),
        migrations.CreateModel(
            name='EduEntryListenStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров файла (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_entry_listen_statistics_months', to='edu.EduEntryListenStatistics', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика просмотров статьи за месяц',
                'verbose_name_plural': 'Статистика просмотров статей за месяц',
            },
        ),
    ]
