# Generated by Django 3.0.9 on 2021-04-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_auto_20210419_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduentrystatistics',
            options={'verbose_name': 'Статистика просмотра статьи', 'verbose_name_plural': 'Статистика просмотров статей'},
        ),
    ]
