# Generated by Django 3.0.9 on 2021-04-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_auto_20210419_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduentrylistenstatisticsmonth',
            options={'verbose_name': 'Статистика прослушиваний статьи за месяц', 'verbose_name_plural': 'Статистика прослушиваний статей за месяц'},
        ),
    ]
