# Generated by Django 3.0.9 on 2021-04-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_auto_20210429_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduentryfilestatistics',
            name='edu_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_entry_file_statistics', to='edu.EduEntry', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='eduentrylistenstatistics',
            name='edu_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_entry_listen_statistics', to='edu.EduEntry', verbose_name='Статья'),
        ),
    ]
