# Generated by Django 3.0.9 on 2020-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.FileField(null=True, upload_to='main/icons', verbose_name='Иконка'),
        ),
    ]
