# Generated by Django 3.0.9 on 2020-08-05 10:57

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empheads_set', to='main.Section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
            },
        ),
        migrations.CreateModel(
            name='EmpSubhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheads_set', to='employment.EmpHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Субглава',
                'verbose_name_plural': 'Субглавы',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=128, unique=True, verbose_name='Ссылка')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_set', to='employment.EmpHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Сайт для поиска работы',
                'verbose_name_plural': 'Сайты для поиска работы',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_subheads_set', to='employment.EmpSubhead')),
            ],
            options={
                'verbose_name': 'Др. информация',
                'verbose_name_plural': 'Др. информация',
            },
        ),
        migrations.CreateModel(
            name='EmpEntryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('photo', models.FileField(upload_to='', verbose_name='Файл')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/')),
                ('subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empentries_set', to='employment.EmpSubhead', verbose_name='Субглава')),
            ],
            options={
                'verbose_name': 'Статья с аудио и фото',
                'verbose_name_plural': 'Статьи с аудио и фото',
            },
        ),
        migrations.CreateModel(
            name='EmpEntryAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/')),
                ('subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empentries_audio_set', to='employment.EmpSubhead', verbose_name='Субглава')),
            ],
            options={
                'verbose_name': 'Статья с аудио',
                'verbose_name_plural': 'Статьи с аудио',
            },
        ),
    ]
