# Generated by Django 3.0.9 on 2020-08-05 11:11

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100, verbose_name='Категория')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Курс')),
                ('company', models.CharField(default='', max_length=100, verbose_name='Название организации/компании')),
                ('phone', models.CharField(default='', max_length=13, verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Почта')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Адрес')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AlterField(
            model_name='other',
            name='subhead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_subheads_set', to='employment.EmpSubhead', verbose_name='Субглава'),
        ),
    ]
