# Generated by Django 3.0.9 on 2020-08-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20200805_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empsubhead',
            options={'verbose_name': 'Подглава', 'verbose_name_plural': 'Подглавы'},
        ),
        migrations.AlterField(
            model_name='empentryaudio',
            name='subhead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empentries_audio_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
        migrations.AlterField(
            model_name='empentryphoto',
            name='subhead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empentries_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
        migrations.AlterField(
            model_name='other',
            name='subhead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_subheads_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
    ]
