# Generated by Django 3.0.9 on 2020-08-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20200805_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='subhead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
        migrations.AlterField(
            model_name='empentryaudio',
            name='subhead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empentries_audio_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
        migrations.AlterField(
            model_name='empentryphoto',
            name='subhead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empentries_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
        migrations.AlterField(
            model_name='other',
            name='subhead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_set', to='employment.EmpSubhead', verbose_name='Подглава'),
        ),
    ]
