# Generated by Django 3.0.9 on 2020-08-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200806_1124'),
        ('employment', '0004_auto_20200807_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emphead',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empheads_set', to='main.Section', verbose_name='Раздел'),
        ),
    ]
