# Generated by Django 3.0.9 on 2020-08-07 08:11

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_auto_20200807_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empentryphoto',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='employment/'),
        ),
    ]
