# Generated by Django 3.0.9 on 2020-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_auto_20200807_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='employment/audio'),
        ),
        migrations.AlterField(
            model_name='empentryaudio',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='employment/audio'),
        ),
        migrations.AlterField(
            model_name='empentryphoto',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='employment/audio'),
        ),
        migrations.AlterField(
            model_name='empentryphoto',
            name='photo',
            field=models.FileField(upload_to='employment/photos', verbose_name='Файл'),
        ),
    ]
