# Generated by Django 3.0.9 on 2020-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_auto_20200813_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=250, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.CharField(default='', max_length=250, verbose_name='Название организации/компании'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='empentryaudio',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='empentryphoto',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='emphead',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='empsubhead',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='other',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Заголовок'),
        ),
    ]
