# Generated by Django 3.0.9 on 2020-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_auto_20200814_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empentryphoto',
            options={'verbose_name': 'Резюме/заявление', 'verbose_name_plural': 'Резюме/заявление'},
        ),
        migrations.AddField(
            model_name='emphead',
            name='type',
            field=models.CharField(choices=[('site', 'Сайт'), ('sub', 'Подтема')], default='site', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='empsubhead',
            name='type',
            field=models.CharField(choices=[('resume_application', 'Резюме/заявление'), ('audio', 'Аудиозапись'), ('course', 'Курс'), ('different', 'Другая информация')], default='resume_application', max_length=20, verbose_name='Тип'),
        ),
    ]
