# Generated by Django 3.0.9 on 2020-09-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0010_auto_20200904_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emphead',
            name='type',
            field=models.CharField(choices=[('site', 'Сайты'), ('sub', 'Подглавы')], default='site', max_length=20, verbose_name='Тип'),
        ),
    ]
