# Generated by Django 3.0.9 on 2020-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0011_auto_20200904_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='empentryphoto',
            name='step',
            field=models.CharField(default='', max_length=100, verbose_name='Шаг'),
        ),
        migrations.AlterField(
            model_name='emphead',
            name='type',
            field=models.CharField(choices=[('site', 'Сайты'), ('info', 'Полезная информация'), ('audio', 'Статьи с аудио'), ('course', 'Курсы')], default='site', max_length=20, verbose_name='Тип'),
        ),
    ]
