# Generated by Django 3.0.9 on 2020-10-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0012_auto_20200921_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='subhead',
        ),
        migrations.AddField(
            model_name='other',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_set', to='employment.EmpHead', verbose_name='Подглава'),
        ),
    ]
