# Generated by Django 3.0.9 on 2020-11-11 10:44

import base.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0014_auto_20201005_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='empentryaudio',
            name='audio_file_kg',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='employment/audio', verbose_name='Аудио (кырг.)'),
        ),
        migrations.AddField(
            model_name='empentryaudio',
            name='file_kg',
            field=base.extra.ContentTypeRestrictedFileField(blank=True, help_text='Допустимый формат - .pdf', null=True, upload_to='employment/documents', verbose_name='Файл (кырг.)'),
        ),
        migrations.AddField(
            model_name='empentryphoto',
            name='audio_file_kg',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='employment/audio', verbose_name='Аудио (кырг.)'),
        ),
    ]
