# Generated by Django 3.0.9 on 2020-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0015_auto_20201111_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audio_image',
            field=models.FileField(blank=True, null=True, upload_to='employment/images', verbose_name='Фото для аудио'),
        ),
        migrations.AddField(
            model_name='empentryaudio',
            name='audio_image',
            field=models.FileField(blank=True, null=True, upload_to='employment/images', verbose_name='Фото для аудио'),
        ),
        migrations.AddField(
            model_name='empentryphoto',
            name='audio_image',
            field=models.FileField(blank=True, null=True, upload_to='employment/images', verbose_name='Фото для аудио'),
        ),
    ]
