# Generated by Django 3.0.9 on 2021-04-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0018_empentryaudiostatistics_empentryaudiostatisticsmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpEntryAudioFileStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_entry_file_statistics', to='employment.EmpEntryAudio', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний файла статьи',
                'verbose_name_plural': 'Статистика скачиваний файла статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='empentryaudiostatistics',
            options={'verbose_name': 'Статистика просмотра статей', 'verbose_name_plural': 'Статистика просмотра статьи'},
        ),
        migrations.AlterModelOptions(
            name='empentryaudiostatisticsmonth',
            options={'verbose_name': 'Статистика просмотра статьи за месяц', 'verbose_name_plural': 'Статистика просмотра статьи за месяц'},
        ),
        migrations.CreateModel(
            name='EmpEntryAudioFileStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний файла (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний файла (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_entry_file_statistics_months', to='employment.EmpEntryAudioFileStatistics', verbose_name='')),
            ],
            options={
                'verbose_name': 'Статистика скачивания файла статьи за месяц',
                'verbose_name_plural': 'Статистика скачивания файла статьи за месяц',
            },
        ),
    ]
