# Generated by Django 3.0.9 on 2021-04-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0020_empentryaudiostatistics_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpEntryAudioListenStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_entry_listen_statistics', to='employment.EmpEntryAudio', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика прослушиваний статьи',
                'verbose_name_plural': 'Статистика прослушиваний статей',
            },
        ),
        migrations.AlterModelOptions(
            name='empentryaudiofilestatistics',
            options={'verbose_name': 'Статистика скачиваний файла статьи', 'verbose_name_plural': 'Статистика скачиваний файлов статей'},
        ),
        migrations.CreateModel(
            name='EmpEntryAudioListenStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_entry_listen_statistics_months', to='employment.EmpEntryAudioListenStatistics', verbose_name='')),
            ],
            options={
                'verbose_name': 'Статистика прослушиваний статьи за месяц',
                'verbose_name_plural': 'Статистика прослушиваний статьи за месяц',
            },
        ),
    ]
