# Generated by Django 3.0.9 on 2021-04-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0021_auto_20210419_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empentryaudiostatistics',
            options={'verbose_name': 'Статистика просмотра статей', 'verbose_name_plural': 'Статистика просмотров статей'},
        ),
    ]
