# Generated by Django 3.0.9 on 2021-04-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownloadStatisticsAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний приложения Android',
                'verbose_name_plural': 'Статистика скачиваний приложения Android',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadStatisticsIOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний приложения IOS',
                'verbose_name_plural': 'Статистика скачиваний приложения IOS',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadsIOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistics_vmeste.AppDownloadStatisticsIOS', verbose_name='Статистика месяца IOS')),
            ],
            options={
                'verbose_name': 'Скачивание',
                'verbose_name_plural': 'Скачивания',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadsAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistics_vmeste.AppDownloadStatisticsAndroid', verbose_name='Статистика месяца Android')),
            ],
            options={
                'verbose_name': 'Скачивание',
                'verbose_name_plural': 'Скачивания',
            },
        ),
    ]
