# Generated by Django 3.0.9 on 2021-04-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20210112_1530'),
        ('statistics_vmeste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEntryViewsStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_entry_statistics', to='info.InfoEntry', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика просмотра статей',
                'verbose_name_plural': 'Статистика просмотра статей',
            },
        ),
        migrations.AlterField(
            model_name='appdownloadsandroid',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appdownloadsandroid',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='android_downloads', to='statistics_vmeste.AppDownloadStatisticsAndroid', verbose_name='Статистика месяца Android'),
        ),
        migrations.AlterField(
            model_name='appdownloadsios',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ios_downloads', to='statistics_vmeste.AppDownloadStatisticsIOS', verbose_name='Статистика месяца IOS'),
        ),
        migrations.CreateModel(
            name='InfoEntryViewsStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_month', to='statistics_vmeste.InfoEntryViewsStatistics', verbose_name='Статистика статьи')),
            ],
            options={
                'verbose_name': 'Статистика статьи за месяц',
                'verbose_name_plural': 'Статистика статьи за месяц',
            },
        ),
    ]
