# Generated by Django 3.0.9 on 2021-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_vmeste', '0003_auto_20210417_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdownloadstatisticsandroid',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего скачиваний за этот месяц'),
        ),
        migrations.AddField(
            model_name='appdownloadstatisticsios',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего скачиваний за этот месяц'),
        ),
    ]
