# Generated by Django 3.0.9 on 2020-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_login', models.CharField(help_text='С учетом регистра!', max_length=128, unique=True, verbose_name='Логин Telegram')),
                ('telegram_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Telegram получатель',
                'verbose_name_plural': 'Telegram получатели',
            },
        ),
    ]
