# Generated by Django 3.0.9 on 2021-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_feedbackapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackapplication',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата поступления заявки'),
        ),
    ]
