# Generated by Django 3.0.9 on 2020-08-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
    ]
