# Generated by Django 3.0.9 on 2020-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200813_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='head',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Краткая информация'),
        ),
        migrations.AlterField(
            model_name='head',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
    ]
