# Generated by Django 3.0.9 on 2020-11-11 07:07

import base.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200814_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='audio_file_kg',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/audio', verbose_name='Аудио (кырг.)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='file_kg',
            field=base.extra.ContentTypeRestrictedFileField(blank=True, help_text='Допустимый формат - .pdf', null=True, upload_to='base/documents', verbose_name='Файл (кырг.)'),
        ),
    ]
