# Generated by Django 3.0.9 on 2021-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_entry_audio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность аудио'),
        ),
        migrations.AddField(
            model_name='entry',
            name='audio_duration_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность аудио (кырг.)'),
        ),
    ]
