# Generated by Django 3.0.9 on 2021-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность аудио в секундах'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='audio_duration_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность аудио в секундах (кырг.)'),
        ),
    ]
