# Generated by Django 3.0.9 on 2021-04-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_entrystatistics_entrystatisticsmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryFileStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_file_statistics', to='base.Entry', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний файла статьи',
                'verbose_name_plural': 'Статистика скачиваний файла статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='entrystatisticsmonth',
            options={'verbose_name': 'Статистика статьи за месяц', 'verbose_name_plural': 'Статистика статьи за месяц'},
        ),
        migrations.CreateModel(
            name='EntryFileStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний файла (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний файла (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_file_statistics_months', to='base.EntryFileStatistics', verbose_name='Статистика статьи')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний файла за месяц',
                'verbose_name_plural': 'Статистика скачиваний файла за месяц',
            },
        ),
    ]
