# Generated by Django 3.0.9 on 2021-04-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210417_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryListenStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_listen_statistics', to='base.Entry', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика прослушиваний статьи',
                'verbose_name_plural': 'Статистика прослушиваний статей',
            },
        ),
        migrations.AlterModelOptions(
            name='entrystatistics',
            options={'verbose_name': 'Статистика просмотров статьи', 'verbose_name_plural': 'Статистика просмотров статьи'},
        ),
        migrations.AddField(
            model_name='entrystatistics',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего просмотров'),
        ),
        migrations.CreateModel(
            name='EntryListenStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний статьи (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний статьи (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_listen_statistics_months', to='base.EntryListenStatistics', verbose_name='Статистика статьи')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний файла за месяц',
                'verbose_name_plural': 'Статистика скачиваний файла за месяц',
            },
        ),
    ]
