# Generated by Django 3.0.9 on 2020-08-05 11:46

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Краткая информация')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoheads_set', to='main.Section', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(null=True, upload_to='uploads/images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_set', to='info.InfoHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='InfoSubhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosubheads_set', to='info.InfoHead', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Подглава',
                'verbose_name_plural': 'Подглавы',
            },
        ),
        migrations.CreateModel(
            name='InfoEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Статья')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='base/')),
                ('subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoentries_set', to='info.InfoSubhead', verbose_name='Подглава')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
