# Generated by Django 3.0.9 on 2020-08-07 07:44

import base.extra
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoentry',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(help_text='Допустимый формат - .pdf', null=True, upload_to='base/documents', verbose_name='Файл'),
        ),
    ]
