# Generated by Django 3.0.9 on 2020-08-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200806_1124'),
        ('info', '0002_infoentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohead',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoheads_set', to='main.Section', verbose_name='Глава'),
        ),
    ]
