# Generated by Django 3.0.9 on 2020-08-13 08:37

import base.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200812_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(blank=True, help_text='Допустимый формат - .pdf', null=True, upload_to='info/documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='infoentry',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='info/audio'),
        ),
        migrations.AlterField(
            model_name='infoentry',
            name='file',
            field=base.extra.ContentTypeRestrictedFileField(help_text='Допустимый формат - .pdf', null=True, upload_to='info/documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='new',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='info/audio', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(null=True, upload_to='info/images/', verbose_name='Фото'),
        ),
    ]
