# Generated by Django 3.0.9 on 2020-09-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20200814_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='infohead',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('sub', 'Подглавы')], default='news', max_length=20, verbose_name='Тип'),
        ),
    ]
