# Generated by Django 3.0.9 on 2020-11-11 11:28

import base.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_infohead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoentry',
            name='audio_file_kg',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='info/audio', verbose_name='Аудио (кырг.)'),
        ),
        migrations.AddField(
            model_name='infoentry',
            name='file_kg',
            field=base.extra.ContentTypeRestrictedFileField(blank=True, help_text='Допустимый формат - .pdf', null=True, upload_to='info/documents', verbose_name='Файл (кырг.)'),
        ),
        migrations.AddField(
            model_name='new',
            name='audio_file_kg',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='info/audio', verbose_name='Аудио (кырг.)'),
        ),
        migrations.AddField(
            model_name='new',
            name='file_kg',
            field=base.extra.ContentTypeRestrictedFileField(blank=True, help_text='Допустимый формат - .pdf', null=True, upload_to='info/documents', verbose_name='Файл (кырг.)'),
        ),
    ]
