# Generated by Django 3.0.9 on 2020-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20201111_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoentry',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Допустимые форматы - .mp3, .wav, .ogg', null=True, upload_to='info/audio', verbose_name='Аудио'),
        ),
    ]
