# Generated by Django 3.0.9 on 2020-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_remove_infoentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoentry',
            name='audio_image',
            field=models.FileField(blank=True, null=True, upload_to='info/images', verbose_name='Фото для аудио'),
        ),
        migrations.AddField(
            model_name='new',
            name='audio_image',
            field=models.FileField(blank=True, null=True, upload_to='info/images', verbose_name='Фото для аудио'),
        ),
    ]
