# Generated by Django 3.0.9 on 2021-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_infoentrystatistics_infoentrystatisticsmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoentrystatistics',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
