# Generated by Django 3.0.9 on 2021-04-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210417_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEntryFileStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_entry_file_statistics', to='info.InfoEntry', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний файла статьи',
                'verbose_name_plural': 'Статистика скачиваний файлов статей',
            },
        ),
        migrations.CreateModel(
            name='InfoEntryFileStatisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статистика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний файла (ru)')),
                ('count_kg', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний файла (kg)')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_entry_file_statistics_month', to='info.InfoEntryFileStatistics', verbose_name='Статистика статьи')),
            ],
            options={
                'verbose_name': 'Статистика скачивания файла статьи за месяц',
                'verbose_name_plural': 'Статистика скачивания файла статьи за месяц',
            },
        ),
    ]
