# Generated by Django 3.0.9 on 2021-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_infoentryfilestatistics_infoentryfilestatisticsmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoentrystatistics',
            options={'verbose_name': 'Статистика просмотра статьи', 'verbose_name_plural': 'Статистика просмотра статей'},
        ),
    ]
