# Generated by Django 3.0.9 on 2021-04-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20210418_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoentrystatistics',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего просмотров'),
        ),
    ]
