# Generated by Django 3.0.9 on 2021-04-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_infoentrylistenstatistics_infoentrylistenstatisticsmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoentrystatistics',
            options={'verbose_name': 'Статистика просмотров статьи', 'verbose_name_plural': 'Статистика просмотров статей'},
        ),
    ]
