# Generated by Django 3.0.9 on 2021-04-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20210429_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoentryfilestatistics',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_news_file_statistics', to='info.New', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='infoentrylistenstatistics',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_news_listen_statistics', to='info.New', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='infoentrystatistics',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_news_statistics', to='info.New', verbose_name='Новость'),
        ),
    ]
